// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2eYklaAPdw-50pcIWyC80iqVM1ZVNQ3A',
    appId: '1:898962222721:web:09492d0bd86a7fc454a780',
    messagingSenderId: '898962222721',
    projectId: 'app-holabella',
    authDomain: 'app-holabella.firebaseapp.com',
    storageBucket: 'app-holabella.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNcVsXfDcdvjJSpFhVcWAvMiskW7q7tr4',
    appId: '1:898962222721:android:be352166ea7a8de354a780',
    messagingSenderId: '898962222721',
    projectId: 'app-holabella',
    storageBucket: 'app-holabella.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnJ6KFUqu4QfYLG0CmTUBt2Y5uiLqtONw',
    appId: '1:898962222721:ios:3e072b0b81166c3e54a780',
    messagingSenderId: '898962222721',
    projectId: 'app-holabella',
    storageBucket: 'app-holabella.appspot.com',
    iosBundleId: 'com.creativex.holabella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnJ6KFUqu4QfYLG0CmTUBt2Y5uiLqtONw',
    appId: '1:898962222721:ios:62c4b8e0f81e607554a780',
    messagingSenderId: '898962222721',
    projectId: 'app-holabella',
    storageBucket: 'app-holabella.appspot.com',
    iosBundleId: 'com.creativex.holabella.RunnerTests',
  );
}
